version: "3.9"
services:
  web:
    container_name: local_unleash
    image: petertolkachev/unleash_4.15.4:latest
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_SSL: "${DATABASE_SSL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      INIT_FRONTEND_API_TOKENS: "${INIT_FRONTEND_API_TOKENS}"
      INIT_CLIENT_API_TOKENS: "${INIT_CLIENT_API_TOKENS}"
      UNLEASH_SIMPLE_STRING: "${UNLEASH_SIMPLE_STRING}"
      ENABLE_REQUEST_LOGGER: "${ENABLE_REQUEST_LOGGER}"
      EMAIL_HOST: "smtp.timeweb.ru"
      EMAIL_PORT: "25"
      EMAIL_SENDER: 'tolkachev@tolkachev.space'
      EMAIL_USER: '${EMAIL_USER}'
      EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
    command: [ "node", "index.js" ]
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
  keycloak:
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres_kk
      DB_DATABASE: keycloack_db
      DB_USER: keycloack
      DB_PASSWORD: "${DB_PASSWORD_KEYCLOAK}"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://keycloak.tolkachev.space/auth
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    restart: always
  pgadmin:
    container_name: local_pgadmin
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: unleash@tolkachev.space
      PGADMIN_DEFAULT_PASSWORD: unleash
    ports:
      - "15432:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin4"
    restart: always
  postgres_unleash:
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_UNLEASH}"
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash_db
    volumes:
      - /root/unleash/data:/var/lib/postgresql/data
      - /root/unleash/backups:/backups
  postgres_kk:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_KEYCLOAK}"
      POSTGRES_USER: keycloack
      POSTGRES_DB: keycloack_db
    volumes:
      - /root/unleash/data-postgres_kk:/var/lib/postgresql/data
      - /root/unleash/backups:/backups

volumes:
  pgadmin:
