version: "3.9"
services:
  web:
    container_name: local_unleash
    image: petertolkachev/unleash_4.15.4:latest
    ports:
      - "4242:4242"
    environment:
      # This points Unleash to its backing database (defined in the `db` section below)
      DATABASE_URL: "postgres://unleash:JuuYQW7iYJaJbm5@postgres_unleash/unleash_db"
      # Disable SSL for database connections. @chriswk: why do we do this?
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "debug"
      # Proxy clients must use one of these keys to connect to the
      # Proxy. To add more keys, separate them with a comma (`key1,key2`).
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # Initialize Unleash with a default set of client API tokens. To
      # initialize Unleash with multiple tokens, separate them with a
      # comma (`token1,token2`).
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
      # не менять!
      UNLEASH_SIMPLE_STRING: "c2VjcmV0"
      ENABLE_REQUEST_LOGGER: "true"
    command: [ "node", "index.js" ]
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
  keycloak:
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres_kk
      DB_DATABASE: keycloack_db
      DB_USER: keycloack
      DB_PASSWORD: wOuCc%K.8jW.2q
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://keycloak.tolkachev.space/auth
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    restart: always
  pgadmin:
    container_name: local_pgadmin
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: unleash@tolkachev.space
      PGADMIN_DEFAULT_PASSWORD: unleash
    ports:
      - "15432:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin4"
    restart: always
  postgres_unleash:
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: JuuYQW7iYJaJbm5
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash_db
    volumes:
      - /root/unleash/data:/var/lib/postgresql/data
      - /root/unleash/backups:/backups
  postgres_kk:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: wOuCc%K.8jW.2q
      POSTGRES_USER: keycloack
      POSTGRES_DB: keycloack_db
    volumes:
      - /root/unleash/data-postgres_kk:/var/lib/postgresql/data
      - /root/unleash/backups:/backups

volumes:
  pgadmin:
