name: Deploy buy runner

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: leitop2k/unleash_4.15.4:latest
  deploy:
    runs-on: self-hosted
    needs: build-push
    steps:
      - name: docker-compose
        run: |
          ls -s
          docker-compose down 
          docker-compose up -d
          docker-compose pull 
          docker-compose up -d