name: Deploy buy runner

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: leitop2k/unleash_4.15.4:latest
  deploy:
    runs-on: self-hosted
    needs: build-push
    steps:
      - uses: actions/checkout@v2
      - name: docker leitop2k/unleash_4.15.4:latest pull
        run: |
          docker pull leitop2k/unleash_4.15.4:latest
      - name: docker restart unleash4154-web-1
        run: |
          docker restart unleash4154-web-1
      - name: docker-compose ps
        run: |
          docker ps