name: Deploy buy runner

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: leitop2k/unleash_4.15.4:latest
  deploy:
    runs-on: self-hosted
    needs: build-push
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose down
        run: |
          docker-compose down
      - name: docker system prune -af
        run: |
          docker container prune -f
          docker image rm $(docker image ls -f dangling=true -q)
      - name: docker-compose up -d
        run: |
          docker-compose up -d