name: Deploy buy runner

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: leitop2k/unleash_4.15.4:latest
  stop-clear:
    runs-on: self-hosted
    needs: build-push
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: stop-clear
    steps:
      - name: checkout repo
        run: docker-compose pull 
      - name: docker-compose
        run: docker-compose up -d